In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("data/Sale Report.csv")

In [4]:
df.head()

   index       SKU Code Design No.  Stock       Category Size Color
0      0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1      1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2      2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3      3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4      4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red

In [7]:
df.shape

(9271, 7)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9271 entries, 0 to 9270
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       9271 non-null   int64
 1   SKU Code    9188 non-null   str
 2   Design No.  9235 non-null   str
 3   Stock       9235 non-null   float64
 4   Category    9226 non-null   str
 5   Size        9235 non-null   str
 6   Color       9226 non-null   str
dtypes: float64(1), int64(1), str(5)
memory usage: 806.1 KB

In [11]:
df.isnull().sum()

index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.describe()

             index        Stock
count  9271.000000  9235.000000
mean   4635.000000    26.246454
std    2676.451507    58.462891
min       0.000000     0.000000
25%    2317.500000     3.000000
50%    4635.000000     8.000000
75%    6952.500000    31.000000
max    9270.000000  1234.000000

In [16]:
df.columns

Index(['index', 'SKU Code', 'Design No.', 'Stock', 'Category', 'Size',
       'Color'],
      dtype='str')

In [18]:
df["Category"].unique()

<ArrowStringArray>
[       'AN : LEGGINGS',               'BLOUSE',                 'PANT',
               'BOTTOM',              'PALAZZO',              'SHARARA',
                'SKIRT',                'DRESS',            'KURTA SET',
        'LEHENGA CHOLI',                  'SET',                  'TOP',
                'KURTA',                    nan,             'CROP TOP',
                'TUNIC',             'CARDIGAN',             'JUMPSUIT',
 'CROP TOP WITH PLAZZO',                'SAREE',                'KURTI',
           'NIGHT WEAR']
Length: 22, dtype: str

In [20]:
df["Category"].value_counts()

Category
KURTA                   3726
KURTA SET               1598
SET                     1050
TOP                      865
DRESS                    700
BLOUSE                   241
NIGHT WEAR               217
TUNIC                    154
SAREE                    147
AN : LEGGINGS            131
PANT                      91
PALAZZO                   91
CROP TOP                  42
SHARARA                   40
LEHENGA CHOLI             35
KURTI                     28
SKIRT                     20
BOTTOM                    19
CARDIGAN                  17
JUMPSUIT                   7
CROP TOP WITH PLAZZO       7
Name: count, dtype: int64

In [24]:
df[df.isnull().any(axis=1)].head(20)

      index SKU Code Design No.  Stock       Category  Size       Color
135     135      NaN      BL086    1.0         BLOUSE  FREE        Blue
142     142      NaN      BL087    0.0         BLOUSE  FREE  Multicolor
197     197      NaN      BL097    1.0         BLOUSE  XXXL      Maroon
198     198      NaN      BL098    2.0         BLOUSE  FREE       Brown
223     223      NaN      BL102    1.0         BLOUSE  FREE   Navy Blue
248     248      NaN      BL109    2.0         BLOUSE  FREE        Gold
273     273      NaN      BL113    0.0         BLOUSE  XXXL      Maroon
546     546      NaN      CH203    0.0  AN : LEGGINGS  FREE      Maroon
901     901      NaN      J0055    0.0            NaN     S         NaN
902     902      NaN      J0055    0.0            NaN    XL         NaN
903     903      NaN      J0055    0.0            NaN    XS         NaN
904     904      NaN      J0055    0.0            NaN   XXL         NaN
938     938      NaN      J0071    0.0            NaN     S         NaN
939     939      NaN      J0071    0.0            NaN    XS         NaN
940     940      NaN      J0071    0.0            NaN  XXXL         NaN
1103   1103      NaN      J0096    1.0          KURTA   4XL        Blue
1104   1104      NaN      J0096    0.0          KURTA   5XL        Blue
1105   1105      NaN      J0096    0.0          KURTA   6XL        Blue
2245   2245      NaN      J0290    0.0       CARDIGAN  XXXL     Mustard
2537   2537      NaN      J0342    0.0            TOP  FREE        Blue

In [25]:
(df.isnull().sum() / len(df)) * 100

index         0.000000
SKU Code      0.895265
Design No.    0.388308
Stock         0.388308
Category      0.485385
Size          0.388308
Color         0.485385
dtype: float64

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df[df["SKU Code"].isnull()].head(10)

     index SKU Code Design No.  Stock       Category  Size       Color
135    135      NaN      BL086    1.0         BLOUSE  FREE        Blue
142    142      NaN      BL087    0.0         BLOUSE  FREE  Multicolor
197    197      NaN      BL097    1.0         BLOUSE  XXXL      Maroon
198    198      NaN      BL098    2.0         BLOUSE  FREE       Brown
223    223      NaN      BL102    1.0         BLOUSE  FREE   Navy Blue
248    248      NaN      BL109    2.0         BLOUSE  FREE        Gold
273    273      NaN      BL113    0.0         BLOUSE  XXXL      Maroon
546    546      NaN      CH203    0.0  AN : LEGGINGS  FREE      Maroon
901    901      NaN      J0055    0.0            NaN     S         NaN
902    902      NaN      J0055    0.0            NaN    XL         NaN

In [28]:
df[df["SKU Code"].isnull()].isnull().sum()

index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

In [29]:
df.tail(10)

      index SKU Code Design No.  Stock Category Size Color
9261   9261      NaN        NaN    NaN      NaN  NaN   NaN
9262   9262      NaN        NaN    NaN      NaN  NaN   NaN
9263   9263      NaN        NaN    NaN      NaN  NaN   NaN
9264   9264      NaN        NaN    NaN      NaN  NaN   NaN
9265   9265      NaN        NaN    NaN      NaN  NaN   NaN
9266   9266      NaN        NaN    NaN      NaN  NaN   NaN
9267   9267      NaN        NaN    NaN      NaN  NaN   NaN
9268   9268      NaN        NaN    NaN      NaN  NaN   NaN
9269   9269      NaN        NaN    NaN      NaN  NaN   NaN
9270   9270      NaN        NaN    NaN      NaN  NaN   NaN

In [30]:
df.drop(columns=["index"]).isnull().all(axis=1).sum()

np.int64(36)

In [31]:
df["SKU Code"].duplicated().sum()

np.int64(100)

In [32]:
df["Size"].value_counts(dropna=False)

Size
S       1353
M       1342
XL      1340
XXL     1338
L       1335
XS      1115
XXXL    1077
FREE     223
5XL       40
6XL       38
NaN       36
4XL       34
Name: count, dtype: int64

In [33]:
df["Color"].value_counts(dropna=False)

Color
Blue            782
Pink            779
Black           659
Green           641
Maroon          485
               ...
CORAL             7
Taupe             6
AQUA GREEN        5
Chiku             1
NO REFERENCE      1
Name: count, Length: 63, dtype: int64

In [37]:
clean_df = df.copy()

In [38]:
clean_df = clean_df.dropna(how="all")

In [39]:
clean_df.shape

(9271, 7)

In [40]:
clean_df.isnull().sum()

index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

In [41]:
clean_df = clean_df.drop(columns=["index"])

In [42]:
clean_df.columns

Index(['SKU Code', 'Design No.', 'Stock', 'Category', 'Size', 'Color'], dtype='str')

In [43]:
clean_df[clean_df["SKU Code"].isnull()]

     SKU Code Design No.  Stock Category  Size       Color
135       NaN      BL086    1.0   BLOUSE  FREE        Blue
142       NaN      BL087    0.0   BLOUSE  FREE  Multicolor
197       NaN      BL097    1.0   BLOUSE  XXXL      Maroon
198       NaN      BL098    2.0   BLOUSE  FREE       Brown
223       NaN      BL102    1.0   BLOUSE  FREE   Navy Blue
...       ...        ...    ...      ...   ...         ...
9266      NaN        NaN    NaN      NaN   NaN         NaN
9267      NaN        NaN    NaN      NaN   NaN         NaN
9268      NaN        NaN    NaN      NaN   NaN         NaN
9269      NaN        NaN    NaN      NaN   NaN         NaN
9270      NaN        NaN    NaN      NaN   NaN         NaN

[83 rows x 6 columns]

In [44]:
clean_df["SKU Code"].isnull().sum()

np.int64(83)

In [45]:
clean_df[clean_df["SKU Code"].isnull()].isnull().sum()

SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

In [46]:
clean_df["SKU Code"].dropna().head(20)

0          AN201-RED-L
1          AN201-RED-M
2          AN201-RED-S
3         AN201-RED-XL
4        AN201-RED-XXL
5       AN202-ORANGE-L
6       AN202-ORANGE-M
7       AN202-ORANGE-S
8      AN202-ORANGE-XL
9     AN202-ORANGE-XXL
10      AN203-MAROON-L
11      AN203-MAROON-M
12      AN203-MAROON-S
13     AN203-MAROON-XL
14    AN203-MAROON-XXL
15      AN204-PURPLE-L
16      AN204-PURPLE-M
17      AN204-PURPLE-S
18     AN204-PURPLE-XL
19    AN204-PURPLE-XXL
Name: SKU Code, dtype: str

In [48]:
clean_df["SKU Code"].nunique()

9170